---
title: "Applications"
---

<!-- ::: {.callout-note}
Apply using the online form [here](https://docs.google.com/forms/d/e/1FAIpQLSctI5Dw7VhUmVKQxSj7lPwGWCvEKU3oI5YlRi0Y1MihDKTXGg/viewform).
::: -->

More details about the transnational access scheme grants can be found on the [ATRIUM Project website](https://atrium-research.eu/travel-grants/){.external}.

## Key dates 

|                               |                                |
|-----------------------------  |--------------------------------|
| March 2025                    | Call for participants opens    |
| **31 May 2025**               | **Deadline for applications**  |
| 2 July 2025                   | Acceptance notifications sent  |
| **15--19 September 2025**     | **Training school**            |
| mid-October 2025 (?)          | Deadline for submission of reports |
| end of November 2025          | Grants paid before this date   |

: {tbl-colwidths="[30,70]"}

<!-- ::: -->

## Who should apply

::: {.callout-tip}

## Note

Only applicants with institutional affiliation **outside of the Czech Republic** are eligible to receive funding due to the *trans-national* nature of the access to the infrastructure provided by the school.
:::

We welcome applications from early-career researchers and students who are enthusiastic about acquiring skills associated with *3D models in archaeology*. This course will focus on the creation, processing, and analysis of 3D data to enhance archaeological research and documentation. Participants should demonstrate a keen interest in digital methods and the integration of 3D models into archaeological interpretation and presentation.

While applicants with prior experience in 3D modeling are encouraged to apply, the first day(s) of training will be dedicated to mastering fundamental concepts and tools. Individuals who are complete beginners are welcome as well, as no prior experience is necessary. <!--Additionally, applicants should have a basic understanding of archaeological documentation and spatial data to fully benefit from the training.-->


## How to apply

Submit your applications through an [**online form**](https://docs.google.com/forms/d/e/1FAIpQLSctI5Dw7VhUmVKQxSj7lPwGWCvEKU3oI5YlRi0Y1MihDKTXGg/viewform){.external}. 
On the 4th page of the application (*TNA Scheme*), choose **'Summer School Access'** and **'Archaeological Information System of the Czech Republic, Institute of Archaeology of the Czech Academy of Sciences, Brno -- AIS CR (ARUB)'** as the proposed host organisation.
On the next page (*Summer School Application*) please explain why you believe this training would be valuable for your research and how you intend to integrate these newfound skills into your work.

More details on how to apply can be found [here](https://atrium-research.eu/transnational-access-scheme-application-process-summer-schools){.external}.
